"""Initial marketplace schema

Revision ID: 3d01ddaf208c
Revises: 
Create Date: 2026-09-27 00:04:22.054824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d01ddaf208c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('buyer', 'freelancer', 'admin')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index('ix_users_role_status', ['role', 'status'], unique=False)

    op.create_table('gigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_gigs_status'),
    sa.CheckConstraint('budget >= 0', name='ck_gigs_budget_nonnegative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.create_index('ix_gigs_category_status', ['category', 'status'], unique=False)
        batch_op.create_index('ix_gigs_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_gigs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gig_id', sa.Integer(), nullable=False),
    sa.Column('freelancer_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timeline', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected')", name='ck_proposals_status'),
    sa.CheckConstraint('proposed_price >= 0', name='ck_proposals_price_nonnegative'),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gig_id', 'freelancer_id', name='uq_proposals_gig_freelancer')
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index('ix_proposals_freelancer_status', ['freelancer_id', 'status'], unique=False)
        batch_op.create_index('ix_proposals_gig_status', ['gig_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_proposals_gig_status')
        batch_op.drop_index('ix_proposals_freelancer_status')

    op.drop_table('proposals')
    op.drop_table('profiles')
    with op.batch_alter_table('gigs', schema=None) as batch_op:
        batch_op.drop_index('ix_gigs_status_created')
        batch_op.drop_index('ix_gigs_owner_status')
        batch_op.drop_index('ix_gigs_category_status')

    op.drop_table('gigs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_status')
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
