"""Add Security Lab mode framework

Revision ID: 5b2b99e598a8
Revises: 3d01ddaf208c
Create Date: 2026-09-27 01:04:38.479347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2b99e598a8'
down_revision = '3d01ddaf208c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_key', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), server_default='mitigated', nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('vulnerable', 'mitigated')", name='ck_security_modes_mode'),
    sa.CheckConstraint("vulnerability_key IN ('sqli', 'stored_xss', 'reflected_xss', 'idor_bola', 'csrf', 'file_upload', 'path_traversal', 'clickjacking', 'auth_session', 'security_misconfiguration')", name='ck_security_modes_vulnerability_key'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_security_modes_updated_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vulnerability_key', name='uq_security_modes_vulnerability_key')
    )
    op.bulk_insert(
        sa.table(
            'security_modes',
            sa.column('vulnerability_key', sa.String(length=64)),
            sa.column('mode', sa.String(length=16)),
            sa.column('updated_by', sa.Integer()),
        ),
        [
            {"vulnerability_key": "sqli", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "stored_xss", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "reflected_xss", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "idor_bola", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "csrf", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "file_upload", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "path_traversal", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "clickjacking", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "auth_session", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "security_misconfiguration", "mode": "mitigated", "updated_by": None},
        ],
    )

    with op.batch_alter_table('security_modes', schema=None) as batch_op:
        batch_op.create_index('ix_security_modes_updated_by', ['updated_by'], unique=False)

    op.create_table('lab_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_key', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("mode IN ('vulnerable', 'mitigated')", name='ck_lab_runs_mode'),
    sa.CheckConstraint("result IN ('not_implemented', 'passed', 'blocked', 'failed')", name='ck_lab_runs_result'),
    sa.ForeignKeyConstraint(['vulnerability_key'], ['security_modes.vulnerability_key'], name='fk_lab_runs_vulnerability_key', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_runs', schema=None) as batch_op:
        batch_op.create_index('ix_lab_runs_key_created_at', ['vulnerability_key', 'created_at'], unique=False)

    op.create_table('security_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_key', sa.String(length=64), nullable=False),
    sa.Column('previous_mode', sa.String(length=16), nullable=False),
    sa.Column('new_mode', sa.String(length=16), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("new_mode IN ('vulnerable', 'mitigated')", name='ck_security_audit_new_mode'),
    sa.CheckConstraint("previous_mode IN ('vulnerable', 'mitigated')", name='ck_security_audit_previous_mode'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='fk_security_audit_changed_by', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vulnerability_key'], ['security_modes.vulnerability_key'], name='fk_security_audit_vulnerability_key', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_security_audit_changed_by', ['changed_by'], unique=False)
        batch_op.create_index('ix_security_audit_key_changed_at', ['vulnerability_key', 'changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_security_audit_key_changed_at')
        batch_op.drop_index('ix_security_audit_changed_by')

    op.drop_table('security_audit_log')
    with op.batch_alter_table('lab_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_lab_runs_key_created_at')

    op.drop_table('lab_runs')
    op.bulk_insert(
        sa.table(
            'security_modes',
            sa.column('vulnerability_key', sa.String(length=64)),
            sa.column('mode', sa.String(length=16)),
            sa.column('updated_by', sa.Integer()),
        ),
        [
            {"vulnerability_key": "sqli", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "stored_xss", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "reflected_xss", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "idor_bola", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "csrf", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "file_upload", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "path_traversal", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "clickjacking", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "auth_session", "mode": "mitigated", "updated_by": None},
            {"vulnerability_key": "security_misconfiguration", "mode": "mitigated", "updated_by": None},
        ],
    )

    with op.batch_alter_table('security_modes', schema=None) as batch_op:
        batch_op.drop_index('ix_security_modes_updated_by')

    op.drop_table('security_modes')
    # ### end Alembic commands ###
